import React from 'react';
import { useLocation, Link, Navigate } from 'react-router-dom';
import { BrainCircuit, ArrowLeft, Bot, Building2, AlertOctagon } from 'lucide-react';

const AIAnalysis = () => {
  const location = useLocation();
  const complaint = location.state?.complaint;

  if (!complaint) {
    return <Navigate to="/complaints" />;
  }

  const getPriorityColor = (priority) => {
    switch(priority) {
      case 'Critical': return 'text-red-400 bg-red-400/10 border-red-400/50';
      case 'High': return 'text-orange-400 bg-orange-400/10 border-orange-400/50';
      case 'Medium': return 'text-yellow-400 bg-yellow-400/10 border-yellow-400/50';
      default: return 'text-green-400 bg-green-400/10 border-green-400/50';
    }
  };

  return (
    <div className="max-w-4xl mx-auto py-8">
      <Link to="/complaints" className="flex items-center text-gray-400 hover:text-white mb-6 transition-colors w-max">
        <ArrowLeft className="w-4 h-4 mr-2" /> Back to Portal
      </Link>
      
      <div className="glass-panel overflow-hidden relative">
        <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-blue-500 via-purple-500 to-blue-500"></div>
        
        <div className="p-8 border-b border-white/10 flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
          <div>
            <div className="flex items-center gap-3 mb-2">
              <BrainCircuit className="w-8 h-8 text-purple-400" />
              <h2 className="text-3xl font-bold">AI Case Analysis</h2>
            </div>
            <p className="text-gray-400">Automated intelligence report generated by Google Gemini / Inference Engine.</p>
          </div>
          <div className={`px-4 py-2 rounded-xl border ${getPriorityColor(complaint.priority)} flex items-center gap-2 font-bold`}>
            <AlertOctagon className="w-5 h-5" />
            {complaint.priority} Priority
          </div>
        </div>

        <div className="p-8 grid grid-cols-1 md:grid-cols-2 gap-8">
          <div className="space-y-6">
            <div>
              <h3 className="text-lg font-semibold text-gray-300 mb-2 border-b border-white/10 pb-2">Original Submission</h3>
              <div className="bg-slate-900 p-4 rounded-xl border border-white/5">
                <p className="font-bold text-white mb-1">{complaint.title}</p>
                <p className="text-gray-400 text-sm">{complaint.description}</p>
              </div>
            </div>
            
            <div>
              <h3 className="text-lg font-semibold text-gray-300 mb-2 border-b border-white/10 pb-2">Routing Determination</h3>
              <div className="flex items-center gap-4 bg-blue-500/10 border border-blue-500/30 p-4 rounded-xl">
                <div className="bg-blue-500/20 p-3 rounded-lg"><Building2 className="text-blue-400 w-6 h-6" /></div>
                <div>
                  <p className="text-sm text-blue-300 font-medium">Assigned Department</p>
                  <p className="text-xl font-bold text-white">{complaint.department}</p>
                </div>
              </div>
            </div>
          </div>
          
          <div className="space-y-6">
            <div>
              <h3 className="text-lg font-semibold text-gray-300 mb-2 border-b border-white/10 pb-2">AI Summary Context</h3>
              <div className="bg-purple-500/10 border border-purple-500/30 p-4 rounded-xl relative">
                <Bot className="absolute top-4 right-4 text-purple-400/50 w-8 h-8" />
                <p className="text-gray-200 pr-10">{complaint.aiSummary || "Summary processing completed."}</p>
              </div>
            </div>
            
            <div>
              <h3 className="text-lg font-semibold text-gray-300 mb-2 border-b border-white/10 pb-2">Automated Official Response</h3>
              <div className="bg-white/5 p-4 rounded-xl border border-white/10 border-l-4 border-l-green-500 italic text-gray-300">
                "{complaint.aiResponse || "Your request has been logged and assigned to the appropriate authority."}"
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AIAnalysis;
